version: '3'
services:
  artillery:
    image: artilleryio/artillery:latest
    volumes:
      - ./scenarios/${TEST_SCENARIO}.yaml:/tests/${TEST_SCENARIO}.yaml
      - "./test_results/:/tests/results/"
    command:
      [
        "run",
        "/tests/${TEST_SCENARIO}.yaml",
        "-o",
        "/tests/results/${TEST_SCENARIO}.json"
      ]
    networks:
      - ${NETWORK}

networks:
  api_trabalho_graduacao_api-tg:
    external: true
