version: '3'
services:
  artillery:
    image: artilleryio/artillery:latest
    volumes:
      - ./script_teste_no_cached.yaml:/testes/script_teste_no_cached.yaml
    command: ["run", "/testes/script_teste_no_cached.yaml"]

networks:
  minha_rede:
